# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Netcore-Smartech-iOS-SDK'
  # Pods for ExampleProject
  
 

end
target 'Service Extention' do
    pod 'Netcore-Smartech-iOS-SDK'
end


target 'Content Extention' do
    pod 'Netcore-Smartech-iOS-SDK'
end
